### ISSUE TITLE
Error Rebuilding

### ISSUE THREAD

**Issue by lm166796** [0xEnrico/arweave-nft-uploader#5]
Keep getting error reuploading below is a snippet from when the error began

Processing file: 15500
Processing file: 15550
Writing indices 0-9
Writing indices 1000-1009
Writing indices 2000-2009
Writing indices 3000-3009
Writing indices 4000-4009
Writing indices 5000-5009
Writing indices 6000-6009
Writing indices 7000-7009
Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'range end index 2651 out of range for slice of length 496', nft-candy-machine/src/lib.rs:318:18
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (C:\Users\Lm166\Documents\Potato\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\Lm166\Documents\Potato\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (C:\Users\Lm166\Documents\Potato\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\Lm166\Documents\Potato\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (C:\Users\Lm166\Documents\Potato\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 2651 out of range for slice of length 496', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]

Side note: Big thanks to the developer @0xEnrico , I've sent some AR tokens to your wallet for your help and contribution to the community.

**Comment by lm166796** [comment]
Note: tried this two ways

First:
Uploaded single asset in assets folder
-ran arweave uploader for full assets
-copied full assets to single assets folder
-ran upload candy machine to rebuild
---above error given--

Second:
Uploaded single asset from single asset folder
-updated the mainnet-beta-temp file with data from arweave temp file (minus the id and  config)
-ran upload to rebuild candy machine
---same error as above--

**Comment by 0xEnrico** [comment]
That is a candy machine error, maybe you should ask in the discord, because I don't know the exact reason why it fails.

Your first procedure was correct. The candy machine needs to rebuild indexes at the end, both with my uploader and with its own uploader.

Here an error similar to yours, they say it's caused by not enough SOL: https://support.solanium.io/support/solutions/articles/69000377685-error-processing-instruction-1-custom-program-error-0x1
