### ISSUE TITLE
Error: failed to get info about account 

### ISSUE THREAD

**Issue by weck25** [0xEnrico/arweave-nft-uploader#8]
INFO Upload complete! Now you can update the index with 'candy-machine-cli.ts upload' using the full assets directory (see documentation) arweave all look right

and i found this when i start the next steps

 ```
ts-node src/candy-machine-cli.ts upload metafak -k /home/bom/.config/solana/metafak.json --env mainnet-beta
Beginning the upload for 3636 (png+json) pairs
started at: 1637300223041
wallet public key: 9BNJRejrb1Rsd1We5nJsCTsA1htdb8StFNLhD8nUt21Z
(node:375) UnhandledPromiseRejectionWarning: Error: failed to get info about account 63N3bBDCVVzdCaofQAnY5s4kcZodw1evomptDgNQ4feK: FetchError: request to https://api.mainnet-beta.solana.com/ failed, reason: connect ECONNREFUSED 128.0.113.154:443
    at Connection.getAccountInfo (/home/bom/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2404:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.fetchIdl (/home/bom/metaplex/js/node_modules/@project-serum/anchor/src/program/index.ts:309:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:375) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:375) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by 0xEnrico** [comment]
This is a candy machine error, can't do much about it, except retrying

Il ven 19 nov 2021, 06:54 weck25 ***@***.***> ha scritto:

**Comment by weck25** [comment]
I've tried it many times but the only thing that comes out is an error

**Comment by patelmax784** [comment]
> I've tried it many times but the only thing that comes out is an error

some news? i have this error too(((
